on:
  push:
    branches:
      - orphan-gha
jobs:
  crawler_job:
    runs-on: ubuntu-latest
    name: A job to crawl website for links
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.3.0
        with:
          provider: 'github'
          token: ${{ secrets.GH_TOKEN }} # It's your Personal Access Token(PAT)
          repository: 'orphan-gha'             # Default is current repository
          branch: 'orphan-gha'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          bundler_ver: '>=0'         # Default is latest bundler version
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux)
      - name: crawler action step
        run: |
          export LOG=log.txt
          export URL=https://open-horizon.github.io/
          wget --no-directories --mirror --spider "$URL" 2>&1 | tee "$LOG";
          crawled_links=(`grep -P -o -e '(?<=^--....-..-.. ..:..:..--  )(.*)' "$LOG"`);
          ls;
          # repo_links=$(ls -R | grep ".html\|.js\|.css\|.png\|.md\|.scss");
          # echo $repo_links;
          # orphan_pages_open_horizon=$(echo ${crawled_links[@]} ${repo_links[@]} | tr ' ' '\n' | sort | uniq -u)
          # echo "The orphan pages are : "
          # echo $orphan_pages_open_horizon
