on: [push]

jobs:
  crawler_job:
    runs-on: ubuntu-latest
    name: A job to crawl website for links
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: crawler action step
        run: |
          export LOG=log.txt
          export URL=https://open-horizon.github.io/
          wget --no-directories --mirror --spider "$URL" 2>&1 | tee "$LOG";
          arr2=(`grep -P -o -e '(?<=^--....-..-.. ..:..:..--  )(.*)' "$LOG"`);
          echo ${arr2[*]}
