on: [push]

jobs:
  crawler_job:
    runs-on: ubuntu-latest
    name: A job to crawl website for links
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: crawler action step
        run: |
          export LOG=log.txt
          export URL=https://open-horizon.github.io/
          wget --no-directories --mirror --spider "$URL" 2>&1 | tee "$LOG";
          crawled_links=(`grep -P -o -e '(?<=^--....-..-.. ..:..:..--  )(.*)' "$LOG"`);
          ls;
          # repo_links=$(ls -R | grep ".html\|.js\|.css\|.png\|.md\|.scss");
          # echo $repo_links;
          # orphan_pages_open_horizon=$(echo ${crawled_links[@]} ${repo_links[@]} | tr ' ' '\n' | sort | uniq -u)
          # echo "The orphan pages are : "
          # echo $orphan_pages_open_horizon
