on: [push]

jobs:
  crawler_job:
    runs-on: ubuntu-latest
    name: A job to crawl website for links
    steps:
      - name: crawler action step
        id: crawler
        uses: MOLOCH-dev/jekyll-orphan-pages-action@v1
        with:
          start-url: 'https://open-horizon.github.io/'
      # Use the output from the `hello` step
      - name: Get the output urls
        run: echo "The crawled urls were ${{ steps.crawler.outputs.crawled-urls }}"
